### ISSUE TITLE
Sticky closes and moves.

### ISSUE THREAD

**Issue by WriterStat** [donShakespeare/tinymceBubbleBar#2]
Hi! I'm starting to mess around with the tinymce editor and ran into your script.

I'm new to tinymce from using quilljs.  

Fun, cool code.

One thing I noticed is when sticky, if you select some new text the bubble menu unsticks and hides then shows up over the new selected text. Doesn't stay stuck to spot. Then sticks again after in the new position. And so on. Could the sticky stay, meaning be sticky where originally stuck and be usable on the next selected text without moving? Thanks! 

Goal would be to be able to leave the sticky bubble menu on the screen in original stuck spot and then edit and or be able to grab/drag sticky bubble menu to a spot where it wouldn't cause any trouble while writing and using it, keeping it viewable. =)

Just curious, would be way cool. I'm guessing to get it to stick it would just mean checking if stuck on text selection and no hide/redraw of sticky bubble if so. But haven't checked the code yet.

Thoughts? Thanks!

-C

**Comment by donShakespeare** [comment]
Thanks for feedback.
Via API you can stick the toolbar to place on the screen. It is also as simple as having a CSS rule in your page stylesheet that forces !important to the sticky class. `position: fixed!important` comes to mind.

That said, I made it move around by default, so that it followed my scrolling. If it stayed stuck up, I'd lose sight of it (if not using CSS fixed rule).
And I did not implement a fixed rule by default because of the huge variety of users' environment - I let them choose.

Users who work in ExtJS environment know how hideous predefined HTML structure can be.

Still, I will look at the script and see how things can be bettered. Keep using and keep thinking, and add more feedback.

Cheers.

**Comment by WriterStat** [comment]
Will give it a try and some thought. Thanks for the insight. And the help. Always glad when I can talk to the author. Super cool!

Following the scroll is great and much needed. 

For larger pages of text bubble menus work great.

Sticky and draggable up in the corner could be cool for large pages of text. Will give fixed a try.

Thanks again!

And for the insight and thoughts.

Cheers,
